# Generated by Django 4.2.1 on 2023-05-11 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character_sheets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character_sheet',
            name='user_sub',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
